#workflow名字

name: MacTask

#在push *.md文件后执行任务

on:

  push:

    paths:

    - '**.md'

jobs:

  build:

    runs-on: macOS-latest

    

    steps:

    

    #输出虚拟机的环境变量,非常有用

    - name: LogAllEnv

      run: printenv

    

    #引用外部Action,拉取代码仓库到虚拟机工作目录

    - uses: actions/checkout@v1
      

    #编译Android运行库,由于Mac预装了NDK,可以直接用;

    #Windows上要下载ndk,下载速度非常快,忽略不计,但解压需要时间,所以直接在Mac编译Android

    - name: BuildAndroid

      run: sh ./BuildAndroid.sh  

